version: '3.8'

services:
  redis:
    image: "redis:8.0.3-bookworm"
    container_name: cleanforum_redis
    command: redis-server --appendonly yes
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  redis-test:
    image: "redis:8.0.3-bookworm"
    container_name: cleanforum_redis_test
    ports:
      - "6381:6379"
    volumes:
      - redis_test_data:/data  # Отдельный volume
    restart: "no"  # Для тестового контейнера

volumes:
  redis_data:
  redis_test_data:  # Добавляем второй volume